/*ARBY SHPIRAGU
ASSIGNMENT 2*/

-
CREATE SCHEMA ASSIGNMENT2;
-

-
CREATE TABLE REP.ASSIGNMENT2
(
	REPNO INTEGER,
	REP_FNAME VARCHAR(50),
	REP_LNAME VARCHAR(50),
	REP_SIN VARCHAR(9),
	CONSTRAINT PK_REPNO PRIMARY KEY(REPNO),
	CONSTRAINT UNQ_REP_SIN UNIQUE(REP_SIN)
);

CREATE TABLE CUSTOMER.ASSIGNMENT2
(
	CUSTNO INTEGER,
	CUST_FNAME VARCHAR(50),
	CUST_LNAME VARCHAR(50),
	CITY VARCHAR(50) DEFAULT 'city',
	REPNO INTEGER,
	CONSTRAINT PK_CUSTNO.ASSIGNMENT2 PRIMARY KEY(CUSTNO),
	CONSTRAINT FK_REPNO.ASSIGNMENT2 FOREIGN KEY(REPNO) 
		REFERENCES REP.ASSIGNMENT2(REPNO)
);

CREATE TABLE ORDERS.ASSINGMENT2
(
	ORDERNO INTEGER,
	ORDER_DATE DATE,
	CUSTNO INTEGER NOT NULL,
	CONSTRAINT PK_ORDERNO.ASSIGNMENT2 PRIMARY KEY(ORDERNO),
	CONSTRAINT FK_CUSTNO.ASSIGNMENT2 FOREIGN KEY(CUSTNO) 
		REFERENCES CUSTOMER(CUSTNO)
);

CREATE TABLE PART.ASSIGNMENT2
(
	PARTNO VARCHAR(25),
	PART_DESC VARCHAR(100),
	WAREHOUSE_NAME VARCHAR(50),
	CONSTRAINT PK_PARTNO.ASSIGNMENT2 PRIMARY KEY(PARTNO),
	CONSTRAINT CHK_WAREHOUSE_NAME.ASSIGNMENT2 
		CHECK (WAREHOUSE_NAME IN('TORONTO', 'NEWYORK', 'IBIZA', 'HONGKONG'))
);

CREATE TABLE ORDER_DETAIL.ASSIGNMENT2
(
	ORDERNO INTEGER,
	PARTNO VARCHAR(25),
	QTY_SOLD INTEGER,
	SOLD_PRICE DECIMAL(5, 5),
	CONSTRAINT PK_ORDERNO.ASSIGNMENT2 PRIMARY KEY(ORDERNO, PARTNO),
	CONSTRAINT FK_ORDERNO.ASSIGNMENT2 FOREIGN KEY(ORDERNO)
		REFERENCES ORDERS.ASSIGNMENT2(ORDERNO),
	CONSTRAINT FK_PARTNO.ASSIGNMENT2 FOREIGN KEY(PARTNO)
		REFERENCES PART.ASSIGNMENT2(PARTNO)
);
-

-
INSERT INTO REP.ASSIGNMENT2 
	VALUES(001, 'MERCEDES', 'S', '123456789');
INSERT INTO REP.ASSIGNMENT2 
	VALUES(002, 'CANDY', 'R', '987654321');
INSERT INTO REP.ASSIGNMENT2 
	VALUES(003, 'DESTINY', 'M', '147258369');
INSERT INTO REP.ASSIGNMENT2 
	VALUES(004, 'FERRARI', 'J', '963852741');
INSERT INTO CUSTOMER.ASSIGNMENT2 
	VALUES(001, 'STAR', 'K', 'TORONTO', 001);
INSERT INTO CUSTOMER.ASSIGNMENT2 
	VALUES(002, 'GALAXIA', 'S', 'VANCOUVER', 002);
INSERT INTO CUSTOMER.ASSIGNMENT2 
	VALUES(003, 'SHALISSA', 'H', 'BOGOTA', 003);
INSERT INTO CUSTOMER.ASSIGNMENT2 
	VALUES(004, 'PORSCHA', 'T', 'MONTANA', 003);
INSERT INTO ORDERS.ASSIGNMENT2 
	VALUES(001, '20181201', 1);
INSERT INTO ORDERS.ASSIGNMENT2 
	VALUES(002, '20181102', 2);
INSERT INTO ORDERS.ASSIGNMENT2 
	VALUES(003, '20181003', 3);
INSERT INTO ORDERS.ASSIGNMENT2 
	VALUES(004, '20180904', 4);
INSERT INTO PART.ASSIGNMENT2 
	VALUES('11111', 'TASSLES', 'TORONTO');
INSERT INTO PART.ASSIGNMENT2 
	VALUES('22222', 'HEELS', 'NEWYORK');
INSERT INTO PART.ASSIGNMENT2 
	VALUES('33333', 'PERFUME', 'IBIZA');
INSERT INTO PART.ASSIGNMENT2 
	VALUES('44444', 'GLITTER', 'HONGKONG');
INSERT INTO ORDER_DETAIL.ASSIGNMENT2 
	VALUES(001, '11111', 1, 19.99);
INSERT INTO ORDER_DETAIL.ASSIGNMENT2 
	VALUES(002, '22222', 1, 19.99);
INSERT INTO ORDER_DETAIL.ASSIGNMENT2 
	VALUES(003, '33333', 2, 19.99);
INSERT INTO ORDER_DETAIL.ASSIGNMENT2 
	VALUES(004, '44444', 3, 19.99);
-

-
UPDATE REP.ASSIGNMENT2 SET REP_FNAME = 'THE' 
	WHERE REPNO = 003;
UPDATE REP.ASSIGNMENT2 SET REP_LNAME = 'NEWGUY' 
	WHERE REPNO = 003;
UPDATE CUSTOMER.ASSIGNMENT2 SET CUST_FNAME = 'ORCHID' 
	WHERE CUSTNO = 002;
UPDATE ORDERS.ASSIGNMENT2 SET ORDER_DATE = '2018-12-12' 
	WHERE ORDERNO = 002;
UPDATE PART.ASSIGNMENT2 SET PARTNO = '66666', PART_DESC = 'LIP GLOSS' 
	WHERE PARTNO = '11111';
-

-
DELETE FROM REP.ASSIGNMENT2 
	WHERE REPNO = 001;
DELETE FROM CUSTOMER.ASSIGNMENT2 
	WHERE CUSTNO = 001;
DELETE FROM ORDERS.ASSIGNMENT2 
	WHERE ORDERNO = 001;
DELETE FROM PART.ASSIGNMENT2 
	WHERE PARTNO = '1111';
DELETE FROM ORDER_DETAIL.ASSIGNMENT2 
	WHERE ORDERNO = 001;
-

-
SELECT CUST_FNAME, CUST_LNAME
	FROM CUSTOMER.ASSIGNMENT2 ;
SELECT REP.REP_FNAME, REP.REP_LNAME, CUSTOMER.CUST_FNAME, CUSTOMER.CUST_LNAME 
	FROM REP.ASSIGNMENT2, CUSTOMER.ASSIGNMENT2 
	JOIN CUSTOMER 
	ON REP.REPNO = CUSTOMER.REPNO;
-

-
ALTER TABLE ORDER_DETAIL.ASSIGNMENT2 
	ADD COLUMN RETAIL_PRICE DECIMAL(5, 5);
ALTER TABLE ORDER_DETAIL.ASSIGNMENT2 
	DROP COLUMN WHOLESALE_PRICE;
-

-
CREATE VIEW REPS.ASSIGNMENT2 
	AS SELECT * FROM REP.ASSIGNMENT2 ;
CREATE INDEX NAMEINDEX.ASSIGNMENT2  
	ON CUSTOMER.ASSIGNMENT2 (CUST_FNAME, CUST_LNAME);
-